openapi: 3.0.0
info:
  title: Event Scheduler API
  description: An API for scheduling events.
  version: 1.0.0

paths:
  /events:
    get:
      summary: returns a list of events
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
          required: false
        - in: query
          name: endDate
          schema:
            type: string
          required: false

      responses:
        "200":
          description: "A JSON array of events"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        startDateTime:
          type: string
          format: date-time
        endDateTime:
          type: string
          format: date-time
